#!/bin/bash

if [ -z $1 ]; then
	echo provide day plz
	exit
fi
which_day="$1"
tname=`mktemp`
cp ~/.mozilla/firefox/*.default/cookies.sqlite "$tname"
SQL="select value from moz_cookies where baseDomain='adventofcode.com' and name='session'"
sqlite3 -separator ' ' "$tname" "$SQL" | {
	read sessioncookie
        curl -b session="$sessioncookie" https://adventofcode.com/2021/day/${which_day}/input
}
